/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.PageController;
import java.awt.AWTError;
import java.awt.Color;
import java.awt.font.TextAttribute;
import javax.swing.JPanel;

/**
 *
 * @author aramo
 */
public class Acceso extends javax.swing.JPanel {

    private static Acceso instance;
    
    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
    }
    
    public static Acceso getInstance(){
        if (instance == null) {
            instance = new Acceso();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        centralPanel = new javax.swing.JPanel();
        accesoDNI = new javax.swing.JButton();
        accesoNIE = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        dniRobado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        centralPanel.setBackground(new java.awt.Color(231, 240, 247));
        centralPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 209, 229), 2, true));
        centralPanel.setForeground(new java.awt.Color(255, 255, 255));
        centralPanel.setPreferredSize(new java.awt.Dimension(600, 450));
        centralPanel.setLayout(new java.awt.GridBagLayout());

        accesoDNI.setBackground(new java.awt.Color(0, 51, 132));
        accesoDNI.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        accesoDNI.setForeground(new java.awt.Color(255, 255, 255));
        accesoDNI.setText("Acceso con DNI");
        accesoDNI.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 10, 30));
        accesoDNI.setBorderPainted(false);
        accesoDNI.setContentAreaFilled(false);
        accesoDNI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoDNI.setFocusPainted(false);
        accesoDNI.setOpaque(true);
        accesoDNI.setPreferredSize(new java.awt.Dimension(300, 50));
        accesoDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accesoDNIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accesoDNIMouseExited(evt);
            }
        });
        accesoDNI.addActionListener(this::accesoDNIActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        centralPanel.add(accesoDNI, gridBagConstraints);

        accesoNIE.setBackground(new java.awt.Color(235, 235, 235));
        accesoNIE.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        accesoNIE.setForeground(new java.awt.Color(0, 51, 132));
        accesoNIE.setText("Acceso con NIE");
        accesoNIE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 132), 2, true));
        accesoNIE.setContentAreaFilled(false);
        accesoNIE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accesoNIE.setFocusPainted(false);
        accesoNIE.setOpaque(true);
        accesoNIE.setPreferredSize(new java.awt.Dimension(300, 50));
        accesoNIE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accesoNIEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accesoNIEMouseExited(evt);
            }
        });
        accesoNIE.addActionListener(this::accesoNIEActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        centralPanel.add(accesoNIE, gridBagConstraints);

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Renovación DNI");
        title.setAlignmentY(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 40, 0);
        centralPanel.add(title, gridBagConstraints);

        dniRobado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dniRobado.setForeground(new java.awt.Color(0, 51, 132));
        dniRobado.setText("<html><body style='width: 400px; text-align:center;'>He perdido mi DNI o me lo han robado</body></html>");
        dniRobado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dniRobado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dniRobadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dniRobadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dniRobadoMouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        centralPanel.add(dniRobado, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -31;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(centralPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void accesoDNIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoDNIMouseExited
        accesoDNI.setBackground(new Color(0, 51, 132));
    }//GEN-LAST:event_accesoDNIMouseExited

    private void accesoDNIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoDNIMouseEntered
        accesoDNI.setBackground(new Color(0, 70, 190));
    }//GEN-LAST:event_accesoDNIMouseEntered

    private void accesoNIEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoNIEMouseEntered
        accesoNIE.setBackground(new Color(192, 192, 192));
    }//GEN-LAST:event_accesoNIEMouseEntered

    private void accesoNIEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accesoNIEMouseExited
        accesoNIE.setBackground(new Color(235,235,235));
    }//GEN-LAST:event_accesoNIEMouseExited

    private void accesoNIEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoNIEActionPerformed
        JPanel contenedor = (JPanel) this.getParent();
        PageController control = new PageController(contenedor, PageController.FORMNIE);
        control.actionPerformed(evt);
    }//GEN-LAST:event_accesoNIEActionPerformed

    private void accesoDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoDNIActionPerformed
        JPanel contenedor = (JPanel) this.getParent();
        PageController control = new PageController(contenedor, PageController.FORMDNI);
        control.actionPerformed(evt);
    }//GEN-LAST:event_accesoDNIActionPerformed

    private void dniRobadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniRobadoMouseClicked
        JPanel contenedor = (JPanel) this.getParent();
        PageController control = new PageController(contenedor, PageController.FORMDNI_OLVIDADO);
        control.actionPerformed(null);
    }//GEN-LAST:event_dniRobadoMouseClicked

    private void dniRobadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniRobadoMouseEntered
        dniRobado.setForeground(new Color(0, 70, 190));
    }//GEN-LAST:event_dniRobadoMouseEntered

    private void dniRobadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dniRobadoMouseExited
        dniRobado.setForeground(new Color(0, 51, 132));
    }//GEN-LAST:event_dniRobadoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accesoDNI;
    private javax.swing.JButton accesoNIE;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JLabel dniRobado;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
