/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.PageController;
import java.awt.Color;
import javax.swing.JPanel;
import utils.Utils;

/**
 *
 * @author aramo
 */
public class Ayuda extends javax.swing.JPanel {

    private static Ayuda instance;

    /**
     * Creates new form Landing
     */
    public Ayuda() {
        initComponents();
    }

    public static Ayuda getInstance() {
        if (instance == null) {
            instance = new Ayuda();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        centralPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        textoIzq = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        centralPanel.setBackground(new java.awt.Color(231, 240, 247));
        centralPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 209, 229), 2, true));
        centralPanel.setForeground(new java.awt.Color(255, 255, 255));
        centralPanel.setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Ayuda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 30, 0);
        centralPanel.add(title, gridBagConstraints);

        textoIzq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textoIzq.setForeground(new java.awt.Color(0, 0, 0));
        textoIzq.setText("<html>\n<div style='width: 480px; text-align: justified; font-family: Arial; color: #000000; line-height: 1.4;'>\n  \n  <b style='color: #003384; font-size: 15px;'> 1. El primer paso: Iniciar el trámite</b><br>\n  Para comenzar cualquier gestión, lo primero que debes hacer es pulsar el botón \"Iniciar trámite\" que encontrarás en la pantalla principal. Esto te llevará a la zona segura de identificación.<br><br>\n\n  <b style='color: #003384; font-size: 15px;'> 2. ¿Cómo puedo acceder al sistema?</b><br>\n  Una vez dentro, el sistema te ofrecerá tres opciones para identificarte según tu situación actual. Elige la que te corresponda:<br><br>\n\n  <div style='margin-left: 15px;'>\n    <b>• Opción A: Acceso con DNI</b><br>\n    <i>Usa esta opción si eres ciudadano español y tienes tu documento a mano.</i><br>\n    Deberás introducir el número de tu DNI (con la letra), su fecha de validez y el código del Equipo de Expedición (los datos que aparecen en la tarjeta física).<br><br>\n\n    <b>• Opción B: Acceso con NIE</b><br>\n    <i>Usa esta opción si eres extranjero residente en España.</i><br>\n    Deberás introducir tu número de NIE (que empieza por X, Y o Z) junto con el \"Número de soporte\" que aparece en tu tarjeta de residencia verde o física.<br><br>\n\n    <b>• Opción C: ¿Has perdido o te han robado el documento?</b><br>\n    <i>Si no dispones de los datos anteriores porque has perdido tu DNI o tu NIE (o si te lo han sustraído), selecciona el enlace de \"Pérdida o sustracción de documento\".</i><br>\n    El sistema te pedirá unos datos personales básicos para verificar tu identidad y te permitirá continuar con el trámite para poder obtener un duplicado o renovación.\n  </div>\n\n</div>\n</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 20);
        centralPanel.add(textoIzq, gridBagConstraints);

        jLabel1.setBackground(new java.awt.Color(231, 240, 247));
        jLabel1.setForeground(new java.awt.Color(231, 240, 247));
        jLabel1.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        centralPanel.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        add(centralPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centralPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textoIzq;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
