/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.PageController;
import java.awt.Color;
import javax.swing.JPanel;
import utils.Utils;

/**
 *
 * @author adolfo
 */
public class Contacto extends javax.swing.JPanel implements Internationalization {

    private static Contacto instance;

    /**
     * Creates new form Landing
     */
    public Contacto() {
        initComponents();
    }

    public static Contacto getInstance() {
        if (instance == null) {
            instance = new Contacto();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        centralPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        textoIzq = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JTextField();
        AdjuntarArchivo = new javax.swing.JButton();
        EnviarMensaje = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        centralPanel.setBackground(new java.awt.Color(231, 240, 247));
        centralPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 209, 229), 2, true));
        centralPanel.setForeground(new java.awt.Color(255, 255, 255));
        centralPanel.setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Contacto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 30, 0);
        centralPanel.add(title, gridBagConstraints);

        textoIzq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textoIzq.setForeground(new java.awt.Color(0, 0, 0));
        textoIzq.setText("<html>\n<div style='width: 480px; text-align: justified; font-family: Arial; color: #000000; line-height: 1.4;'>\n  \n  <b style='color: #003384; font-size: 15px;'> •Atención Telefónica (060)</b><br>\n  Si prefiere concertar, modificar o anular su cita por teléfono, puede llamar al número de atención ciudadana <b>060</b>.<br>\n  • <i>Horario:</i> Disponible las 24 horas del día, todos los días del año (atención por agente especializado de lunes a viernes de 9:00 a 19:00 h).<br><br>\n\n  <b style='color: #003384; font-size: 15px;'> • Soporte Técnico y Consultas</b><br>\n  Para incidencias con la plataforma web, problemas al tramitar sus datos o consultas sobre la documentación necesaria, puede escribir a la dirección de correo oficial:<br>\n  <div style='margin-left: 15px; margin-top: 4px; margin-bottom: 4px;'>\n    <b>📧 sac@dgp.es</b> (Servicio de Atención al Ciudadano)\n  </div>\n  <i>Por motivos de seguridad, no adjunte copias de sus documentos de identidad en el correo electrónico.</i><br><br>\n\n  <b style='color: #003384; font-size: 15px;'> • Oficinas de Expedición</b><br>\n  Recuerde que los trámites presenciales se realizan exclusivamente en las Jefaturas Superiores y Comisarías de Policía habilitadas. Puede consultar la ubicación y el horario específico de su oficina local durante el proceso de selección de cita en esta web.\n  \n</div>\n</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 20);
        centralPanel.add(textoIzq, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(231, 240, 247));
        jLabel1.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        centralPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("<html>\n<div style='font-family: Arial; font-size: 13px; color: #003384; margin-bottom: 3px;'>\n  <b>Escriba su consulta o reclamación detallada:</b>\n</div>\n</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        centralPanel.add(jLabel2, gridBagConstraints);

        txtMensaje.setBackground(new java.awt.Color(204, 204, 204));
        txtMensaje.setPreferredSize(new java.awt.Dimension(500, 100));
        txtMensaje.addActionListener(this::txtMensajeActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        centralPanel.add(txtMensaje, gridBagConstraints);

        AdjuntarArchivo.setBackground(new java.awt.Color(204, 204, 204));
        AdjuntarArchivo.setForeground(new java.awt.Color(0, 0, 0));
        AdjuntarArchivo.setText("Adjuntar archivo");
        AdjuntarArchivo.addActionListener(this::AdjuntarArchivoActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 200, 0, 0);
        centralPanel.add(AdjuntarArchivo, gridBagConstraints);

        EnviarMensaje.setBackground(java.awt.SystemColor.activeCaption);
        EnviarMensaje.setForeground(new java.awt.Color(255, 255, 255));
        EnviarMensaje.setText("Enviar mensaje");
        EnviarMensaje.addActionListener(this::EnviarMensajeActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 350, 0, 0);
        centralPanel.add(EnviarMensaje, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(231, 240, 247));
        jLabel3.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        centralPanel.add(jLabel3, gridBagConstraints);

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setText("Escriba su dirección de correo");
        jTextField1.setPreferredSize(new java.awt.Dimension(500, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        centralPanel.add(jTextField1, gridBagConstraints);

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.setText("Asunto del mensaje");
        jTextField2.setPreferredSize(new java.awt.Dimension(500, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        centralPanel.add(jTextField2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        add(centralPanel, gridBagConstraints);
    }// </editor-fold>                        

    private void AdjuntarArchivoActionPerformed(java.awt.event.ActionEvent evt) {                                                
        javax.swing.JFileChooser buscador = new javax.swing.JFileChooser();
        int seleccion = buscador.showOpenDialog(this);

        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = buscador.getSelectedFile();
        }
    }                                               

    private void EnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String mensaje = txtMensaje.getText().trim();

        if (mensaje.isEmpty() || mensaje.equals("Escriba su consulta o reclamación detallada:")) {

            javax.swing.JOptionPane.showMessageDialog(this,
                "<html><b style='color: #C0392B; font-family: Arial; font-size: 13px;'>Formulario Incompleto:</b><br>"
                + "<span style='font-family: Arial; font-size: 12px; color: #555555;'>"
                + "Por favor, rellene tanto el asunto como el cuerpo del mensaje antes de realizar el envío.</span></html>",
                "Atención - Policía Nacional",
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.JOptionPane.showMessageDialog(this,
            "<html><b style='color: #003384; font-family: Arial; font-size: 13px;'>Consulta Registrada Correctamente</b><br>"
            + "<span style='font-family: Arial; font-size: 12px; color: #555555;'>"
            + "Su mensaje y documentación adjunta han sido enviados al Servicio de Atención al Ciudadano.<br>"
            + "Recibirá una respuesta en su correo electrónico en un plazo máximo de 48 horas.</span></html>",
            "Envío Exitoso",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        txtMensaje.setText("");
    }                                             

    private void txtMensajeActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }

       @Override
    public void actualizarTextos(ResourceBundle bundle) {
        title.setText(bundle.getString("CONTACTO_TITULO"));
        textoIzq.setText(bundle.getString("CONTACTO_INFO"));
        jLabel2.setText(bundle.getString("CONTACTO_PROMPT"));
        AdjuntarArchivo.setText(bundle.getString("CONTACTO_BTN_ADJUNTAR"));
        EnviarMensaje.setText(bundle.getString("CONTACTO_BTN_ENVIAR"));
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton AdjuntarArchivo;
    private javax.swing.JButton EnviarMensaje;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel textoIzq;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration                   
}
