/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import java.awt.Color;
import java.util.ResourceBundle;

/**
 *
 * @author aramo
 */
public class Contacto extends javax.swing.JPanel implements Internationalization {

    private static Contacto instance;

    /**
     * Creates new form Landing
     */
    public Contacto() {
        initComponents();
    }

    public static Contacto getInstance() {
        if (instance == null) {
            instance = new Contacto();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        centralPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        textoIzq = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensaje = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        AdjuntarArchivo = new javax.swing.JButton();
        EnviarMensaje = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        centralPanel.setBackground(new java.awt.Color(231, 240, 247));
        centralPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 209, 229), 2, true));
        centralPanel.setForeground(new java.awt.Color(255, 255, 255));
        centralPanel.setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Contacto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 30, 0);
        centralPanel.add(title, gridBagConstraints);

        textoIzq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textoIzq.setForeground(new java.awt.Color(0, 0, 0));
        textoIzq.setText("<html>\n<div style='width: 480px; text-align: justified; font-family: Arial; color: #000000; line-height: 1.4;'>\n  \n  <b style='color: #003384; font-size: 15px;'> •Atención Telefónica (060)</b><br>\n  Si prefiere concertar, modificar o anular su cita por teléfono, puede llamar al número de atención ciudadana <b>060</b>.<br>\n  • <i>Horario:</i> Disponible las 24 horas del día, todos los días del año (atención por agente especializado de lunes a viernes de 9:00 a 19:00 h).<br><br>\n\n  <b style='color: #003384; font-size: 15px;'> • Soporte Técnico y Consultas</b><br>\n  Para incidencias con la plataforma web, problemas al tramitar sus datos o consultas sobre la documentación necesaria, puede escribir a la dirección de correo oficial:<br>\n  <div style='margin-left: 15px; margin-top: 4px; margin-bottom: 4px;'>\n    <b>📧 sac@dgp.es</b> (Servicio de Atención al Ciudadano)\n  </div>\n  <i>Por motivos de seguridad, no adjunte copias de sus documentos de identidad en el correo electrónico.</i><br><br>\n\n  <b style='color: #003384; font-size: 15px;'> • Oficinas de Expedición</b><br>\n  Recuerde que los trámites presenciales se realizan exclusivamente en las Jefaturas Superiores y Comisarías de Policía habilitadas. Puede consultar la ubicación y el horario específico de su oficina local durante el proceso de selección de cita en esta web.\n  \n</div>\n</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 20);
        centralPanel.add(textoIzq, gridBagConstraints);

        jLabel1.setForeground(new java.awt.Color(231, 240, 247));
        jLabel1.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        centralPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setText("<html>\n<div style='font-family: Arial; font-size: 13px; color: #003384; margin-bottom: 3px;'>\n  <b>Escriba su consulta o reclamación detallada:</b>\n</div>\n</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        centralPanel.add(jLabel2, gridBagConstraints);

        txtMensaje.setBackground(new java.awt.Color(255, 255, 255));
        txtMensaje.setColumns(20);
        txtMensaje.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtMensaje.setForeground(new java.awt.Color(0, 0, 0));
        txtMensaje.setRows(5);
        jScrollPane1.setViewportView(txtMensaje);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        centralPanel.add(jScrollPane1, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(231, 240, 247));

        AdjuntarArchivo.setBackground(new java.awt.Color(255, 255, 255));
        AdjuntarArchivo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        AdjuntarArchivo.setForeground(new java.awt.Color(0, 51, 132));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources/Bundle_es_ES"); // NOI18N
        AdjuntarArchivo.setText(bundle.getString("CONTACTO_BTN_ADJUNTAR")); // NOI18N
        AdjuntarArchivo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 132)));
        AdjuntarArchivo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AdjuntarArchivo.setPreferredSize(new java.awt.Dimension(200, 45));
        AdjuntarArchivo.addActionListener(this::AdjuntarArchivoActionPerformed);
        jPanel1.add(AdjuntarArchivo);

        EnviarMensaje.setBackground(new java.awt.Color(0, 51, 132));
        EnviarMensaje.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        EnviarMensaje.setForeground(new java.awt.Color(255, 255, 255));
        EnviarMensaje.setText("Enviar mensaje");
        EnviarMensaje.setBorderPainted(false);
        EnviarMensaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EnviarMensaje.setFocusPainted(false);
        EnviarMensaje.setPreferredSize(new java.awt.Dimension(200, 45));
        EnviarMensaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EnviarMensajeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EnviarMensajeMouseExited(evt);
            }
        });
        EnviarMensaje.addActionListener(this::EnviarMensajeActionPerformed);
        jPanel1.add(EnviarMensaje);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 40, 0);
        centralPanel.add(jPanel1, gridBagConstraints);

        jLabel3.setForeground(new java.awt.Color(231, 240, 247));
        jLabel3.setText("jLabel3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        centralPanel.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        add(centralPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void AdjuntarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdjuntarArchivoActionPerformed
        javax.swing.JFileChooser buscador = new javax.swing.JFileChooser();
        javax.swing.filechooser.FileNameExtensionFilter filtroImagen
                = new javax.swing.filechooser.FileNameExtensionFilter(
                        "Archivos de Imagen (JPG, PNG, GIF)", "jpg", "jpeg", "png", "gif"
                );

        buscador.setFileFilter(filtroImagen);

        int seleccion = buscador.showOpenDialog(this);

        if (seleccion == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = buscador.getSelectedFile();
            // Aquí podrías mostrar el nombre del archivo en un label para que el usuario sepa que se adjuntó
            System.out.println("Archivo seleccionado: " + archivo.getName());
        }
    }//GEN-LAST:event_AdjuntarArchivoActionPerformed

    private void EnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarMensajeActionPerformed
        java.util.ResourceBundle bundle = main.Main.getBundle();
        String mensaje = txtMensaje.getText().trim();

        if (mensaje.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    bundle.getString("CONTACTO_ERR_MSG"),
                    bundle.getString("CONTACTO_ERR_TIT"),
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        javax.swing.JOptionPane.showMessageDialog(this,
                bundle.getString("CONTACTO_OK_MSG"),
                bundle.getString("CONTACTO_OK_TIT"),
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        txtMensaje.setText("");

    }//GEN-LAST:event_EnviarMensajeActionPerformed

    private void EnviarMensajeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarMensajeMouseEntered
        EnviarMensaje.setBackground(new Color(0, 70, 190));
    }//GEN-LAST:event_EnviarMensajeMouseEntered

    private void EnviarMensajeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarMensajeMouseExited
        EnviarMensaje.setBackground(new Color(0, 51, 132));
    }//GEN-LAST:event_EnviarMensajeMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdjuntarArchivo;
    private javax.swing.JButton EnviarMensaje;
    private javax.swing.JPanel centralPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel textoIzq;
    private javax.swing.JLabel title;
    private javax.swing.JTextArea txtMensaje;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizarTextos(ResourceBundle bundle) {
        title.setText(bundle.getString("CONTACTO_TITULO"));
        textoIzq.setText(bundle.getString("CONTACTO_INFO"));
        jLabel2.setText(bundle.getString("CONTACTO_PROMPT"));
        AdjuntarArchivo.setText(bundle.getString("CONTACTO_BTN_ADJUNTAR"));
        EnviarMensaje.setText(bundle.getString("CONTACTO_BTN_ENVIAR"));
    }
}
