/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.PageController;
import java.awt.Color;
import java.util.ResourceBundle;
import javax.swing.JPanel;
import utils.Utils;

/**
 *
 * @author aramo
 */
public class Landing extends javax.swing.JPanel implements Internationalization {

    private static Landing instance;

    /**
     * Creates new form Landing
     */
    public Landing() {
        initComponents();
        fotoDNI.setIcon(Utils.getScaledIcon("/images/dni-ejemplo-1.jpg", 300));
    }

    public static Landing getInstance() {
        if (instance == null) {
            instance = new Landing();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        centralPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        textoIzq = new javax.swing.JLabel();
        fotoDNI = new javax.swing.JLabel();
        iniciarTramite = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        centralPanel.setBackground(new java.awt.Color(231, 240, 247));
        centralPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(184, 209, 229), 2, true));
        centralPanel.setForeground(new java.awt.Color(255, 255, 255));
        centralPanel.setLayout(new java.awt.GridBagLayout());

        title.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setText("Renovación DNI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 30, 0);
        centralPanel.add(title, gridBagConstraints);

        textoIzq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textoIzq.setForeground(new java.awt.Color(0, 0, 0));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources/Bundle_es_ES"); // NOI18N
        textoIzq.setText(bundle.getString("TEXTO_LANDING")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 40, 0, 20);
        centralPanel.add(textoIzq, gridBagConstraints);

        fotoDNI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dni-ejemplo-1.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 40);
        centralPanel.add(fotoDNI, gridBagConstraints);

        iniciarTramite.setBackground(new java.awt.Color(0, 51, 132));
        iniciarTramite.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        iniciarTramite.setForeground(new java.awt.Color(255, 255, 255));
        iniciarTramite.setText(bundle.getString("INICIAR_TRAMITE")); // NOI18N
        iniciarTramite.setBorder(null);
        iniciarTramite.setBorderPainted(false);
        iniciarTramite.setContentAreaFilled(false);
        iniciarTramite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iniciarTramite.setFocusPainted(false);
        iniciarTramite.setOpaque(true);
        iniciarTramite.setPreferredSize(new java.awt.Dimension(200, 50));
        iniciarTramite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iniciarTramiteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iniciarTramiteMouseExited(evt);
            }
        });
        iniciarTramite.addActionListener(this::iniciarTramiteActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 30, 0);
        centralPanel.add(iniciarTramite, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 50, 50);
        add(centralPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarTramiteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarTramiteMouseEntered
        iniciarTramite.setBackground(new Color(0, 70, 190));
    }//GEN-LAST:event_iniciarTramiteMouseEntered

    private void iniciarTramiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciarTramiteMouseExited
        iniciarTramite.setBackground(new Color(0, 51, 132));
    }//GEN-LAST:event_iniciarTramiteMouseExited

    private void iniciarTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarTramiteActionPerformed
        JPanel contenedor = (JPanel) this.getParent();
        PageController control = new PageController(contenedor, PageController.ACCESO);
        control.actionPerformed(evt);
    }//GEN-LAST:event_iniciarTramiteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centralPanel;
    private javax.swing.JLabel fotoDNI;
    private javax.swing.JButton iniciarTramite;
    private javax.swing.JLabel textoIzq;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizarTextos(ResourceBundle bundle) {
        title.setText(bundle.getString("RENOVACION_DNI"));
        textoIzq.setText(bundle.getString("TEXTO_LANDING"));
        iniciarTramite.setText(bundle.getString("INICIAR_TRAMITE"));
    }
}
