package main;

import components.Footer;
import components.Header;
import java.awt.BorderLayout;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JPanel;
import views.Acceso;
import views.Ayuda;
import views.Contacto;
import views.FormDNI;
import views.FormDNIOlvidado;
import views.FormNIE;
import views.Landing;
import views.TuOpinion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aramo
 */
public class Main extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());
    private static ResourceBundle bundle;
    private Locale currentLocale;

    /**
     * Creates new form Main
     */
    public Main() {
        currentLocale = Locale.getDefault();
        bundle = ResourceBundle.getBundle("resources.Bundle", currentLocale);

        initComponents();
        this.setSize(1280, 720);

        this.setLocationRelativeTo(null);

        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(20);
        JPanel header = Header.getInstance(this);
        JPanel footer = Footer.getInstance();
        JPanel center = Landing.getInstance();

        this.setTitle(bundle.getString("TITULO"));

        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(header, BorderLayout.NORTH);
        jPanel1.add(footer, BorderLayout.SOUTH);
        jPanel1.add(center, BorderLayout.CENTER);
    }

    public static ResourceBundle getBundle() {
        return bundle;
    }

    public void cambiarIdioma(String lenguaje, String pais) {
        this.currentLocale = Locale.of(lenguaje, pais);

        bundle = ResourceBundle.getBundle("resources.Bundle", currentLocale);

        this.setTitle(bundle.getString("TITULO"));

        Header.getInstance(this).actualizarTextos(bundle);
        Landing.getInstance().actualizarTextos(bundle);
        FormDNI.getInstance().actualizarTextos(bundle);
        FormNIE.getInstance().actualizarTextos(bundle);
        FormDNIOlvidado.getInstance().actualizarTextos(bundle);
        Acceso.getInstance().actualizarTextos(bundle);
        Footer.getInstance().actualizarTextos(bundle);
        Ayuda.getInstance().actualizarTextos(bundle);
        TuOpinion.getInstance().actualizarTextos(bundle);
        Contacto.getInstance().actualizarTextos(bundle);

        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(null);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
