/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import main.Main;
import controllers.PageController;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import utils.Utils;
import views.Internationalization;

/**
 *
 * @author aramo
 */
public class Header extends javax.swing.JPanel implements Internationalization {

    private Main mainApp;
    private static Header instance;

    /**
     * Creates new form Header
     */
    public Header(Main main) {
        mainApp = main;
        initComponents();
        configurarMenuIdiomas();
        try {
            idioma.setIcon(utils.Utils.getScaledIcon("/images/bandera-spain.png", 25));
            idioma.setIconTextGap(10);
            idioma.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        } catch (Exception e) {
            System.err.println("No se pudo cargar la bandera inicial: " + e.getMessage());
        }
        iconoPolicia.setIcon(Utils.getScaledIcon("/images/policia-log-2.png", 275));
    }

    public static Header getInstance(Main main) {
        if (instance == null) {
            instance = new Header(main);
        }
        return instance;
    }

    private void configurarMenuIdiomas() {
        JPopupMenu menu = new JPopupMenu();

        // Opción Español
        JMenuItem itemEs = new JMenuItem("Español", utils.Utils.getScaledIcon("/images/bandera-spain.png", 20));
        itemEs.addActionListener(e -> {
            mainApp.cambiarIdioma("es", "ES"); // Llama al método de Main
            idioma.setIcon(utils.Utils.getScaledIcon("/images/bandera-spain.png", 25));
            idioma.setIconTextGap(10);
            idioma.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        });

        // Opción catalán
        JMenuItem itemCat = new JMenuItem("Català", utils.Utils.getScaledIcon("/images/bandera-catalunya.png", 20));
        itemCat.addActionListener(e -> {
            mainApp.cambiarIdioma("ca", "ES"); // Llama al método de Main
            idioma.setIcon(utils.Utils.getScaledIcon("/images/bandera-catalunya.png", 25));
            idioma.setIconTextGap(10);
            idioma.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        });

        // Opción Inglés
        JMenuItem itemEn = new JMenuItem("English", utils.Utils.getScaledIcon("/images/bandera-uk.png", 20));
        itemEn.addActionListener(e -> {
            mainApp.cambiarIdioma("en", "GB"); // Llama al método de Main
            idioma.setIcon(utils.Utils.getScaledIcon("/images/bandera-uk.png", 25));
            idioma.setIconTextGap(10);
            idioma.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        });

        menu.add(itemEs);
        menu.add(itemCat);
        menu.add(itemEn);

        // Evento para mostrar el menú al clicar en la bandera del Header
        idioma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        });
    }

    @Override
    public void actualizarTextos(java.util.ResourceBundle bundle) {
        inicio.setText(bundle.getString("INICIO"));
        ayuda.setText(bundle.getString("AYUDA"));
        contacto.setText(bundle.getString("CONTACTO"));
        tuOpinion.setText(bundle.getString("TU_OPINION"));
        idioma.setText(bundle.getString("IDIOMA_TITULO"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        iconoPolicia = new javax.swing.JLabel();
        inicio = new javax.swing.JLabel();
        ayuda = new javax.swing.JLabel();
        contacto = new javax.swing.JLabel();
        tuOpinion = new javax.swing.JLabel();
        idioma = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 53, 134));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        iconoPolicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/policia-log-2.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 30, 15, 0);
        add(iconoPolicia, gridBagConstraints);

        inicio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("resources/Bundle_es_ES"); // NOI18N
        inicio.setText(bundle.getString("INICIO")); // NOI18N
        inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(inicio, gridBagConstraints);

        ayuda.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ayuda.setForeground(new java.awt.Color(255, 255, 255));
        ayuda.setText(bundle.getString("AYUDA")); // NOI18N
        ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ayudaMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(ayuda, gridBagConstraints);

        contacto.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        contacto.setForeground(new java.awt.Color(255, 255, 255));
        contacto.setText(bundle.getString("CONTACTO")); // NOI18N
        contacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contactoMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(contacto, gridBagConstraints);

        tuOpinion.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tuOpinion.setForeground(new java.awt.Color(255, 255, 255));
        tuOpinion.setText(bundle.getString("TU_OPINION")); // NOI18N
        tuOpinion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tuOpinion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tuOpinionMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(tuOpinion, gridBagConstraints);

        idioma.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        idioma.setForeground(new java.awt.Color(255, 255, 255));
        idioma.setText(bundle.getString("IDIOMA_TITULO")); // NOI18N
        idioma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 30);
        add(idioma, gridBagConstraints);
    }// </editor-fold>                        

    private void inicioMouseClicked(java.awt.event.MouseEvent evt) {                                    
        JPanel contenedor = (JPanel) this.getParent();
        PageController control = new PageController(contenedor, PageController.LANDING);
        control.actionPerformed(null);
    }                                   

    private void ayudaMouseClicked(java.awt.event.MouseEvent evt) {                                   
        JPanel contenedor = (JPanel) this.getParent();
        PageController control = new PageController(contenedor, PageController.AYUDA);
        control.actionPerformed(null);
    }                                  

    private void contactoMouseClicked(java.awt.event.MouseEvent evt) {                                      
        JPanel contenedor = (JPanel) this.getParent();
        PageController control = new PageController(contenedor, PageController.CONTACTO);
        control.actionPerformed(null);
    }                                     

    private void tuOpinionMouseClicked(java.awt.event.MouseEvent evt) {                                       
        JPanel contenedor = (JPanel) this.getParent();
        PageController control = new PageController(contenedor, PageController.TU_OPINION);
        control.actionPerformed(null);
    }                                      


    // Variables declaration - do not modify                     
    private javax.swing.JLabel ayuda;
    private javax.swing.JLabel contacto;
    private javax.swing.JLabel iconoPolicia;
    private javax.swing.JLabel idioma;
    private javax.swing.JLabel inicio;
    private javax.swing.JLabel tuOpinion;
    // End of variables declaration                   
}
