/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package components;

import controllers.PageController;
import javax.swing.JPanel;
import utils.Utils;

/**
 *
 * @author aramo
 */
public class Header extends javax.swing.JPanel {

    /**
     * Creates new form Header
     */
    public Header() {
        initComponents();
        iconoPolicia.setIcon(Utils.getScaledIcon("/images/policia-log-2.png", 275));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        iconoPolicia = new javax.swing.JLabel();
        inicio = new javax.swing.JLabel();
        ayuda = new javax.swing.JLabel();
        contacto = new javax.swing.JLabel();
        tuOpinion = new javax.swing.JLabel();
        idioma = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 53, 134));
        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridBagLayout());

        iconoPolicia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/policia-log-2.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 30, 15, 0);
        add(iconoPolicia, gridBagConstraints);

        inicio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        inicio.setForeground(new java.awt.Color(255, 255, 255));
        inicio.setText("Inicio");
        inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inicioMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(inicio, gridBagConstraints);

        ayuda.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ayuda.setForeground(new java.awt.Color(255, 255, 255));
        ayuda.setText("Ayuda\n");
        ayuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(ayuda, gridBagConstraints);

        contacto.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        contacto.setForeground(new java.awt.Color(255, 255, 255));
        contacto.setText("Contacto");
        contacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(contacto, gridBagConstraints);

        tuOpinion.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        tuOpinion.setForeground(new java.awt.Color(255, 255, 255));
        tuOpinion.setText("Tu opinión");
        tuOpinion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(tuOpinion, gridBagConstraints);

        idioma.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        idioma.setForeground(new java.awt.Color(255, 255, 255));
        idioma.setText("Idioma");
        idioma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 30);
        add(idioma, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inicioMouseClicked
        JPanel contenedor = (JPanel) this.getParent();
        PageController control = new PageController(contenedor, PageController.LANDING);
        control.actionPerformed(null);
    }//GEN-LAST:event_inicioMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ayuda;
    private javax.swing.JLabel contacto;
    private javax.swing.JLabel iconoPolicia;
    private javax.swing.JLabel idioma;
    private javax.swing.JLabel inicio;
    private javax.swing.JLabel tuOpinion;
    // End of variables declaration//GEN-END:variables
}
